// First-2-Phonemes-to-keystroke codebook
#define KEYS 61
PROGMEM const unsigned char cbp[KEYS][3]={
'_','_','?',  // dummy first entry
'A',  0,'a',
'A','e','a',
'b','E','b',
's','E','c',
'd','E','d',
'E',  0,'e',
'E','A','e',
'e','f','f',
'j','E','g',
'A','j','h',
'A','_','h',
'E','_','h',
'a','e','i',
'j','a','j',
'j','e','j',
'k','A','k',
'e','l','l',
'a','l','l',
'e','m','m',
'e','n','n',
'o',  0,'o',
'w',  0,'o',
'o','w','o',
'w','o','o',
'o','l','o',
'w','l','o',
'w','e','o',
'b','k','p',
'k','O','q',
'k','s','q',
'k','j','q',
'k','E','q',
'a','r','r',
'a','w','r',
'w','r','r',
'e','s','s',
't','E','t',
's','d','t',
's','k','t',
'd','s','t',
'E','O','u',
'y','O','u',
'y','e','u',
'f','E','v',
'v','E','v',
'd','a','w',
'd','u','w',
'b','w','w',
'd','w','w',
'b','_','w',
'd','_','w',
'u','w','w',
'e','_','x',
'w','a','y',
's','e','z',
's','b','_',
'n','o',127,  // backspace
'w','m',1, // turn on
'w','n',1, // turn on
'w','d',0, // turn off
};
